#! /bin/bash
# list all files and directories under root, recursively

SHORT=t:,n:
LONG=type:,name:
OPTS=$(getopt -n lsa -o $SHORT --long $LONG -- "$@")

eval set -- "$OPTS"

cmd="find"
args=()
dir="./"

while :
do
case "${1}" in
    -t | --type)
        args+=("-type")
        args+=("$2")
        shift 2
    ;;
    -n | --name)
        args+=("-name")
        args+=("$2")
        shift 2
    ;;
    --)
        dir="$2"
        shift;
        break;
    ;;
    *)
    ;;
esac
done

cmd+=" $dir ${args[*]}"
eval "$cmd"

exit 0